### ISSUE TITLE
Regarding INPUT parameter 

### ISSUE THREAD

**Issue by Data-Steam** [ChristopherBenjaminHemmens/MintyGrid#1]
Thanks lot for the Great Initiative and sharing the code,
Input Parameter bit confusion will you explain all 5 parameter in plain ENGLISH.
Please Put the parameter for Spread control it will be more efficient.

**Comment by ChristopherBenjaminHemmens** [comment]
Hi, sorry for the late reply. Do you want a parameter to prevent trading when there's a large spread?
